pub mod deposit;
pub mod initialize;
pub mod rebalance;
pub mod report_yield;
pub mod set_params;
pub mod withdraw;

// Glob re-exports are required: the `#[program]` macro references the
// `__client_accounts_*` modules generated by `#[derive(Accounts)]` through
// this path. Handler fns carry unique names to keep the globs unambiguous.
pub use deposit::*;
pub use initialize::*;
pub use rebalance::*;
pub use report_yield::*;
pub use set_params::*;
pub use withdraw::*;
